project:
  type: website

website:
  title: "Christy Coulson"
  description: "Social Data Scientist and Political Methodologist at LSE."
  site-url: "https://christycoulson.github.io"
  image: simbelmyne.jpg
  favicon: favicon.ico
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: other.qmd
        text: Other stuff

format:
  html:
    theme: sandstone
    css: styles.css
    fontsize: 1.05em
    linestretch: 1.6
    mainfont: "EB Garamond"
    monofont: "IBM Plex Mono"